# Netlify Configuration for Next.js 14 Static Export
# This configuration enables successful deployment of the Instagram clone

[build]
  # Build command - runs Next.js production build with static export
  command = "npm run build"
  
  # Publish directory - Next.js static export outputs to 'out' folder
  publish = "out"

# Environment configuration
[build.environment]
  # Next.js 14 requires Node.js 18 or higher
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
