# Netlify Configuration for Next.js 14
# This configuration enables successful deployment of the Instagram clone

[build]
  # Build command - runs Next.js production build
  command = "npm run build"
  
  # Publish directory - Next.js outputs to '.next' folder for SSR
  publish = ".next"

# Environment configuration
[build.environment]
  # Next.js 14 requires Node.js 18 or higher
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Next.js runtime configuration
[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

# Enable Next.js runtime on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
