import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      screens: {
        mobile: { max: '767px' },
        tablet: { min: '768px', max: '1023px' },
        desktop: { min: '1024px' },
        xl: { min: '1280px' },
      },
      colors: {
        'ig-primary': '#0095F6',
        'ig-primary-hover': '#1877F2',
        'ig-primary-light': '#E0F1FF',
        'ig-secondary': '#8E8E8E',
        'ig-bg-primary': '#FAFAFA',
        'ig-bg-secondary': '#FFFFFF',
        'ig-bg-tertiary': '#F5F5F5',
        'ig-text-primary': '#262626',
        'ig-text-secondary': '#8E8E8E',
        'ig-text-tertiary': '#B2B2B2',
        'ig-border': '#DBDBDB',
        'ig-border-light': '#EFEFEF',
        'ig-error': '#ED4956',
        'ig-error-light': '#FFEBEE',
        'ig-success': '#4CAF50',
        'ig-success-light': '#E8F5E9',
        'ig-warning': '#FF9500',
        'ig-warning-light': '#FFF3E0',
        'ig-info': '#0095F6',
        'ig-info-light': '#E3F2FD',
        'ig-gradient-start': '#C13584',
        'ig-gradient-mid': '#E1306C',
        'ig-gradient-end': '#F77737',
        'overlay-dark': 'rgba(0, 0, 0, 0.65)',
        'overlay-light': 'rgba(0, 0, 0, 0.25)',
        'skeleton-base': '#E0E0E0',
        'skeleton-shimmer': '#F5F5F5',
      },
      fontWeight: {
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      lineHeight: {
        tight: '1.2',
        snug: '1.375',
        normal: '1.5',
        relaxed: '1.625',
        loose: '2',
      },
      letterSpacing: {
        tighter: '-0.05em',
        tight: '-0.025em',
        normal: '0',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
      },
      borderRadius: {
        none: '0',
        sm: '3px',
        DEFAULT: '8px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '24px',
        full: '9999px',
      },
      spacing: {
        '0': '0',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
      },
      zIndex: {
        base: '0',
        dropdown: '1000',
        sticky: '1020',
        fixed: '1030',
        modal: '1050',
        tooltip: '1070',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '200ms',
        slow: '300ms',
        slower: '500ms',
      },
      transitionTimingFunction: {
        'ease-in-out-custom': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'ease-out-custom': 'cubic-bezier(0.0, 0, 0.2, 1)',
        'ease-in-custom': 'cubic-bezier(0.4, 0, 1, 1)',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
      },
      boxShadow: {
        'ig-card': '0 0 5px 1px rgba(0, 0, 0, 0.0975)',
        'ig-modal': '0 8px 32px rgba(0, 0, 0, 0.3)',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '200% center' },
          '100%': { backgroundPosition: '-200% center' },
        },
        heartBeat: {
          '0%': { transform: 'scale(1)' },
          '25%': { transform: 'scale(1.2)' },
          '50%': { transform: 'scale(1)' },
          '75%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)' },
        },
        slideUp: {
          from: { transform: 'translateY(40px)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        scaleIn: {
          from: { transform: 'scale(0.95)', opacity: '0' },
          to: { transform: 'scale(1)', opacity: '1' },
        },
      },
      animation: {
        shimmer: 'shimmer 2s infinite linear',
        heartBeat: 'heartBeat 300ms ease-out',
        slideUp: 'slideUp 300ms cubic-bezier(0.4, 0, 0.2, 1)',
        fadeIn: 'fadeIn 200ms ease-in',
        scaleIn: 'scaleIn 200ms cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}

export default config